
@MediOrchestratorAPI_HostAddress = https://localhost:7230

POST {{MediOrchestratorAPI_HostAddress}}/api/Patient/patients
Content-Type: application/json
Accept: application/json
{
  "fullName": "Santosh",
  "gender": "male",
  "mobileNo": "9074392890",
  "bloodGroup": "A +ve",
  "dateOfBirth": "2026-09-05T11:39:07.602Z",
  "address": "yz"
}